### ISSUE TITLE
restore with no arguments throws an error, should print a help message instead

### ISSUE THREAD

**Issue by irvingpop** [chef/chef_backup#8]
```
# chef-server-ctl restore
(eval):75:in `expand_path': no implicit conversion of nil into String (TypeError)
    from (eval):75:in `normalize_arg'
    from (eval):63:in `block in load_file'
    from /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.3.6/lib/omnibus-ctl.rb:181:in `call'
    from /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.3.6/lib/omnibus-ctl.rb:181:in `block in add_command_under_category'
    from /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.3.6/lib/omnibus-ctl.rb:575:in `run'
    from /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.3.6/bin/omnibus-ctl:31:in `<top (required)>'
    from /opt/opscode/embedded/bin/omnibus-ctl:23:in `load'
    from /opt/opscode/embedded/bin/omnibus-ctl:23:in `<main>'
```

**Comment by ryancragun** [comment]
This should be resolved by https://github.com/chef/chef_backup/commit/bd29c56a0adb93c1443201088024b09f42b508a2.  You can track the upstream PR that bundles this fix in the Chef Server here https://github.com/chef/chef-server/pull/770
